In [23]:
#1
#importing required library
import numpy as np
#entering the values into the row vector and column vector manually
a=np.array([5, 9, 11])
b=np.array([[6],
            [9],
            [12]])
print("values in row vector:\n",a)
print("values in column vector:\n",b)

values in row vector:
 [ 5  9 11]
values in column vector:
 [[ 6]
 [ 9]
 [12]]


In [26]:
#1
#taking no of rows required from the user
i=int(input("number of rows:  "))
#defining a empty list
l=[]
for x in range(i):
#taking input from the user using input() method
    v=input()
#adding the values into the empty list
    l.append(v)
#printing the row matrix
print(l)


number of rows:  3
3
1 2
3
['3', '1 2', '3']


In [27]:
#1
#taking  number of columns required from the user
i=int(input("number of columns: "))
#defining empty vector
l= []
for x in range(i):
#taking input from the user using input() method
    v=input()
#adding the values into empty vector
    l.append(v)
#printing the each element in the column vector
for e in l:
    print(e)

number of columns: 2
1 2
1 2
1 2
1 2


In [29]:
#2
#IMPORTING THE REQUIRED LIBRARIES
import numpy as np
#input for number of rows
i=int(input("enter number of rows:  "))
#input for number of columns
j=int(input("enter number of columns:  "))
#empty list for required matrix
y=[]
#for loop for row values
for x in range(i):
#empty list to append the column values
  c=[]
#for loop for column values
  for x in range(j):
#input for the values in the matrix
    v=input()
#adding the values into the empty list
    c.append(v)
#adding all the columns into the empty list y
  y.append(c)
#changing the list into a matrix form
a=np.matrix(y)
print(a)

enter number of rows:  5
enter number of columns:  5
1 2 3 4 5
1 1 1 1 1
1 1 1 1 1
1 1 1 1 1
1 1 1 1 1
1 1 1 1 1


KeyboardInterrupt: ignored

In [30]:
#2
#importing  the required library
import numpy as np
#entering the matrix values manually
a=np.matrix('[1,2,3,4,5;2,4,6,7,9;8,9,5,7,7;2,6,9,0,4;3,7,2,8,1]')
#printing matrix a
print(a)
#3
#printing 3rd row from the matrix
print(a[2])
#4
#printing 4th column from the matrix
print(a[:,3])
#5
#sorting the matrix
a.sort()
print(a)

[[1 2 3 4 5]
 [2 4 6 7 9]
 [8 9 5 7 7]
 [2 6 9 0 4]
 [3 7 2 8 1]]
[[8 9 5 7 7]]
[[4]
 [7]
 [7]
 [0]
 [8]]
[[1 2 3 4 5]
 [2 4 6 7 9]
 [5 7 7 8 9]
 [0 2 4 6 9]
 [1 2 3 7 8]]
