<a href="https://colab.research.google.com/github/CE605A/Shanmukha-Sree-Jaya-Prakash_231030052/blob/main/jp231030052.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
#1
#importing required library
import numpy as np
#entering the values into the row vector and column vector manually
row=np.array([1, 2, 3])
column=np.array([[4],
            [5],
            [6]])
print("values in row vector:\n",row)
print("values in column vector:\n",column)

values in row vector:
 [1 2 3]
values in column vector:
 [[4]
 [5]
 [6]]


In [4]:
#1
#no of rows required in runtime
row_input=int(input("number of rows:  "))
#empty list
l=[]
for x in range(row_input):
#taking input from the user using input() method
    v=input()
#adding the values into the empty list
    l.append(v)
#printing the row matrix
print(l)


number of rows:  3
1
1
1
['1', '1', '1']


In [5]:
#1
#number of columns required in runtime
column_input=int(input("number of columns: "))
#defining empty vector
l= []
for x in range(column_input):
#taking input from the user using input() method
    v=input()
#adding the values into empty vector
    l.append(v)
#printing the each element in the column vector
for e in l:
    print(e)

number of columns: 3
1
2
3
1
2
3


In [6]:
#2
#IMPORTING THE REQUIRED LIBRARIES
import numpy as np
#input for number of rows
row_value=int(input("enter number of rows:  "))
#input for number of columns
column_value=int(input("enter number of columns:  "))
#empty list for required matrix
y=[]
#for loop for row values
for x in range(row_value):
#empty list to append the column values
  c=[]
#for loop for column values
  for x in range(column_value):
#input for the values in the matrix
    v=input()
#adding the values into the empty list
    c.append(v)
#adding all the columns into the empty list y
  y.append(c)
#changing the list into a matrix form
a=np.matrix(y)
print(a)

enter number of rows:  3
enter number of columns:  3
1
2
2
2
2
2
2
2
2
[['1' '2' '2']
 ['2' '2' '2']
 ['2' '2' '2']]


In [30]:
#2
#importing  the required library
import numpy as np
#entering the matrix values manually
a=np.matrix('[1,2,3,4,5;2,4,6,7,9;8,9,5,7,7;2,6,9,0,4;3,7,2,8,1]')
#printing matrix a
print(a)
#3
#printing 3rd row from the matrix
print(a[2])
#4
#printing 4th column from the matrix
print(a[:,3])
#5
#sorting the matrix
a.sort()
print(a)

[[1 2 3 4 5]
 [2 4 6 7 9]
 [8 9 5 7 7]
 [2 6 9 0 4]
 [3 7 2 8 1]]
[[8 9 5 7 7]]
[[4]
 [7]
 [7]
 [0]
 [8]]
[[1 2 3 4 5]
 [2 4 6 7 9]
 [5 7 7 8 9]
 [0 2 4 6 9]
 [1 2 3 7 8]]


In [31]:
#6
#defining matrix A
a= [
    [1,2,3,4,5],
    [2,4,6,7,9],
    [8,9,5,7,7],
    [2,6,9,0,4],
    [3,7,2,8,1]
]

# Applying the for loop to modify the matrix A
for i in range(5):
    for j in range(5):
#as mentioned if the element is greater than 2 it must be multiplied by 10
        if a[i][j] > 2:
            a[i][j] *= 10
            a[i][j] =   str(a[i][j])
print("Modified Matrix:")
b=a
"""for row in matrix:
    print(row)"""
#printing the modified matrix
print(b)

Modified Matrix:
[[1, 2, '30', '40', '50'], [2, '40', '60', '70', '90'], ['80', '90', '50', '70', '70'], [2, '60', '90', 0, '40'], ['30', '70', 2, '80', 1]]


In [32]:
#7
#defining matrix A
a= [
    [1,2,3,4,5],
    [2,4,6,7,9],
    [8,9,5,7,7],
    [2,6,9,0,4],
    [3,7,2,8,1]
]
#defining matrix B
b=[
    [1,2,30,40,50],
    [2,40,60,70,90],
    [80,90,50,70,70],
    [2,60,90,0,40],
    [30,70,2,80,1]]
#defining a 5x5 matrix with all zero
sum=[[0,0,0,0,0],
     [0,0,0,0,0],
     [0,0,0,0,0],
     [0,0,0,0,0],
     [0,0,0,0,0]]
#applying for loop
for i in range(len(a)):
    for j in range(len(a[0])):
#adding corresponding elements from both matrices and storing in the sum matrix
        sum[i][j]=a[i][j]+b[i][j]
#printing every element of the r matrix
for r in sum:
  print(r)

[2, 4, 33, 44, 55]
[4, 44, 66, 77, 99]
[88, 99, 55, 77, 77]
[4, 66, 99, 0, 44]
[33, 77, 4, 88, 2]


In [33]:
#8
#defining matrix A
a= [
    [1,2,3,4,5],
    [2,4,6,7,9],
    [8,9,5,7,7],
    [2,6,9,0,4],
    [3,7,2,8,1]
]
#defining matrix B
b=[
    [1,2,30,40,50],
    [2,40,60,70,90],
    [80,90,50,70,70],
    [2,60,90,0,40],
    [30,70,2,80,1]]
#defining a 5x5 matrix with all zero
sub=[[0,0,0,0,0],
     [0,0,0,0,0],
     [0,0,0,0,0],
     [0,0,0,0,0],
     [0,0,0,0,0]]
#applying for loop
for i in range(len(a)):
    for j in range(len(a[0])):
#substarcting corresponding elements from both matrices and storing in the sub matrix
        sub[i][j]=a[i][j]-b[i][j]
#printing every element of the r matrix
for r in sub:
  print(r)

[0, 0, -27, -36, -45]
[0, -36, -54, -63, -81]
[-72, -81, -45, -63, -63]
[0, -54, -81, 0, -36]
[-27, -63, 0, -72, 0]


In [34]:
#9
#defining matrix A
a= [
    [1,2,3,4,5],
    [2,4,6,7,9],
    [8,9,5,7,7],
    [2,6,9,0,4],
    [3,7,2,8,1]
]
#defining matrix B
b=[
    [1,2,30,40,50],
    [2,40,60,70,90],
    [80,90,50,70,70],
    [2,60,90,0,40],
    [30,70,2,80,1]]
#defining a 5x5 matrix with all zero
multi=[[0,0,0,0,0],
       [0,0,0,0,0],
       [0,0,0,0,0],
       [0,0,0,0,0],
       [0,0,0,0,0]]
#applying for loop
for i in range(len(a)):
    for j in range(len(a[0])):
#multiplying corresponding elements from both matrices and storing in the multi matrix
        multi[i][j]=a[i][j]*b[i][j]
#printing every element of the multi matrix
for r in multi:
  print(r)

[1, 4, 90, 160, 250]
[4, 160, 360, 490, 810]
[640, 810, 250, 490, 490]
[4, 360, 810, 0, 160]
[90, 490, 4, 640, 1]


In [35]:
#9
#defining matrix A
a= [
    [1,2,3,4,5],
    [2,4,6,7,9],
    [8,9,5,7,7],
    [2,6,9,0,4],
    [3,7,2,8,1]
]
#defining matrix B
b=[
    [1,2,30,40,50],
    [2,40,60,70,90],
    [80,90,50,70,70],
    [2,60,90,0,40],
    [30,70,2,80,1]]
#defining a 5x5 matrix with all zero
result=[[0,0,0,0,0],
         [0,0,0,0,0],
         [0,0,0,0,0],
         [0,0,0,0,0],
         [0,0,0,0,0]]
#applying for loop
for i in range(len(a)):
    for j in range(len(b[0])):
        for k in range(len(b)):
#performing matrix multiplication
            result[i][j]+=a[i][k]*b[k][j]
#printing every element from the result
for row in result:
    print(row)

[403, 942, 670, 790, 605]
[774, 1754, 1248, 1500, 1169]
[650, 1736, 1674, 1860, 1847]
[854, 1334, 878, 1450, 1274]
[223, 1016, 1332, 830, 1241]


In [36]:
#10
#importing all the required libraries
import numpy as np
a = np.array([[1,2,3,4,5],
              [2,4,6,7,9],
              [8,9,5,7,7],
              [2,6,9,0,4],
              [3,7,2,8,1]])
# Divide every element of the matrix by 18
result = a / 18
# Print the result
print(result)

[[0.05555556 0.11111111 0.16666667 0.22222222 0.27777778]
 [0.11111111 0.22222222 0.33333333 0.38888889 0.5       ]
 [0.44444444 0.5        0.27777778 0.38888889 0.38888889]
 [0.11111111 0.33333333 0.5        0.         0.22222222]
 [0.16666667 0.38888889 0.11111111 0.44444444 0.05555556]]


In [37]:
#11
#importing the required library
#using linalg means linear algebra
import numpy as np
#calculating rank of the matrix
np.linalg.matrix_rank(a)
#calculating inverse of the matrix
np.linalg.inv(a)
#calculating the condition number
np.linalg.cond(a)
#calculating the single value decomposition
np.linalg.svd(a)
#calculating the norm
np.linalg.norm(a)

27.80287754891569

In [38]:
#11
#importing the required library
#using linalg means linear algebra
import numpy as np
#calculating rank of the matrix
np.linalg.matrix_rank(b)
#calculating inverse of the matrix
np.linalg.inv(b)
#calculating the condition number
np.linalg.cond(b)
#calculating the single value decomposition
np.linalg.svd(b)
#calculating the norm
np.linalg.norm(b)

274.8053856823043

In [39]:
#12
#importing the required library
import numpy as np
# Define the column vector
a=np.array([
    [5],
    [9],
    [11]
])
#calculating the norm
norm = np.linalg.norm(a)
print(" norm of the column vector:",norm)

 norm of the column vector: 15.066519173319364


In [40]:
#12
#importing the required library
import numpy as np
# Define the column vectors
a=np.array([
    [5],
    [9],
    [11]
])
b=np.array([
    [6],
    [9],
    [12]
])
#getting inner product of the vector
i_product = np.dot(a.T,b)
print("inner product:",i_product)

inner product: [[243]]


In [42]:
#12
#importing the required libraries
import numpy as np
# Define the column vectors
a=np.array([
    [5],
    [9],
    [11]
])
b=np.array([
    [6],
    [9],
    [12]
])
#getting outer product of the vectors
o_product = np.outer(a,b.T)
print("outer product:\n",o_product)

outer product:
 [[ 30  45  60]
 [ 54  81 108]
 [ 66  99 132]]


In [43]:
#13
#importing the required library
import math
#defining the function derivative
def derivative(f,a,method='central',h=0.01):
#applying if loop and giving the conditions
    if method == 'forward':
        return (f(a+h)-f(a))/h
#applying the elif conditions
    elif method == 'backward':
        return (f(a)-f(a-h))/h
#applying the elif conditions
    elif method == 'central':
        return (f(a+h)-f(a-h))/(2*h)
#applying the else and giving conditions
    else:
        raise ValueError("Invalid method. Use 'forward', 'backward', or 'central'.")
# Test the function on exp(x) and cos(x) at x = 0.5
x = 0.5
exp = derivative(math.exp, x)
cos = derivative(math.cos, x)

print("Derivative of exp(x)", x, ":",exp)
print("Derivative of cos(x)", x, ":",cos)

Derivative of exp(x) 0.5 : 1.648748749525375
Derivative of cos(x) 0.5 : -0.4794175482185081


In [57]:
#14
#importing the required library
import pandas as pdp
#reading the csv file and copying the path of the required csv file
df=pd.read_csv("/surface_data.csv")
#printing the data frame
print(df)

         obstime     tempr        ap      ws       wd       rh
0     1985-02-26  -10.0000  983.0250  16.125   11.750   64.875
1     1985-02-27  -12.6250  981.5750   5.875   29.250   58.625
2     1985-02-28  -17.1875  983.7750   3.000   99.000   55.125
3     1985-03-01 -507.6250  986.3375  19.125 -493.625 -999.000
4     1985-03-02 -257.3125  497.7500  33.875 -243.000 -224.125
...          ...       ...       ...     ...      ...      ...
9380  2010-12-27   -0.1125  996.9375   5.625   15.750 -999.000
9381  2010-12-28   -0.7000  994.6750  19.250    9.750 -999.000
9382  2010-12-29    0.6375  994.2875  22.250   10.250 -999.000
9383  2010-12-30    1.4375  992.5125  14.500   10.250 -999.000
9384  2010-12-31    0.9500  989.2000  16.500   11.500 -999.000

[9385 rows x 6 columns]
